notifications:
  email: false

dist: trusty

sudo: false

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

language: node_js
node_js:
  - "8.10.0"

script:
  - ./script/test
